### PR TITLE
Test send message + fixing a minor bug in /lark

### LINKED ISSUE #112: these are bitwise ORs. Should also be closing audiostream
these are bitwise ORs. Should also be closing audiostream

_Originally posted by @aldew5 in https://github.com/CSC207-2023Y-UofT/course-project-larklink/pull/110#discussion_r1278672876_

### PR DESCRIPTION
**Pull request by weihan1**
-Created tests for MessageController, MessageInteractor, and MessagePresenter. I wasn't able to cover the lark tests in MessageInteractor (as commented and explained in the MessageInteractorTest). 
-Fixed a small bug where if the user refreshes the page and /lark was in the messageHistory then the sound would be played. Changed it to if the last sent message instead contains /lark then the sound would be played.
-Tried to resolve #112 by closing the audio stream. Don't know how to solve the Bitwise OR thing.

### CODE REVIEW

**Review by vincecloutier — DISMISSED** [review]

**Review by margaretpell — APPROVED** [review]

File: src/main/java/messaging/MessageDBGateway.java [hunk 1]
```diff
@@ -1,8 +1,22 @@
...
+    /**
+     * Retrieves a RoomDBModel object for the given room ID from the database.
+     *
+     * @param roomID The ID of the room to retrieve from the database.
+     * @return The RoomDBModel object representing the room retrieved from the database.
+     */
     RoomDBModel getARoom(Integer roomID);
+
+    /**
+     * Sends a RoomDBModel object representing a room to the database.
```
Comment (chelkisea) [inline src/main/java/messaging/MessageDBGateway.java:17]: we no longer have `sendAMessage` method in `MessageDbGateway`. Please check out main branch and edit this document after you resolve merge conflict.

File: src/test/java/messaging/MessageInteractorTest.java [hunk 2]
```diff
@@ -0,0 +1,118 @@
...
+//        // Verify that the presenter method is called with the correct message history
+//        verify(presenter).prepareRoomView(messageHistory);
+//
+//        doNothing().when(messageInteractor).playLarkSound();
+//        //Verify that the interactor plays the lark sound
+//        verify(messageInteractor).playLarkSound();
+//    }
+}
+// Commented the lark testing because verify(...) is only allowed for mock but messageInteractor is not a mock
+// A solution was to make messageInteractor a spy, that did pass the test but didn't pass the auto-grading.
```
Comment (chelkisea) [inline src/test/java/messaging/MessageInteractorTest.java:116]: add this to issue

**Review by chelkisea — APPROVED** [review]
I don't think you need to handle bitwise OR in this case since using | instead of || is the right syntax for multiple exceptions.

**Review by vincecloutier — APPROVED** [review]

**Review by chelkisea — APPROVED** [review]

**Review by margaretpell — APPROVED** [review]
